from utils.screen import clear, warn, message, error
from utils.collect import Collector
from utils.piloterror import PilotError
from src.data import Data
from src.model import PilotNet
import carla, random, time, datetime

class Menu():

    def run_1():
        'Train using generated data'
        data = Data()
        message('Data collection finished')

        # this is some nasty code here, will have to be cleaned up
        message('How much epochs do you wanna train the model? The default is 30.')
        epochs = int(input('Enter epochs >> ') or 30)
        message('How much steps do you wanna run per epoch? The default is 10.')
        steps = int(input('Enter steps >> ') or 10)
        message('How many steps do you wanna run for validation? The default is 10.')
        steps_val = int(input('Enter steps >> ') or 10)
        message('Enter the batch size to use for training. The default is 64')
        batch_size = int(input('Enter size >> ') or 64)
        message('Give a filename for the model. Skip to use an autogenerated name.')
        name = input('Enter a name >> ') or f"{epochs}epochs_{steps}perepoch_{datetime.datetime.now().strftime('@%Y-%m-%d-%H:%M')}"
        message('Enter the frame dimensions of images. Note that higher sizes consume higher memory')
        width = input('Enter width (default 160) >> ') or 160
        height = input('Enter height (default 120) >> ') or 120

        clear()
        try:
            message(f'Starting tensorflow model with {width}x{height} images')
            pilotnet = PilotNet(width, height)
        except:
            raise PilotError('Oops, that didnt work. System might be out of memory. Try again with smaller dimensions.')
        clear()
        message('Starting training')
        try:
            pilotnet.train(name, data, epochs, steps, steps_val, batch_size)
        except:
            raise PilotError('Some unexpected error occured during training. Please try again.')

    def run_2():
        'Generate new data'
        message('Connecting to CARLA world')
        client = carla.Client('localhost', 2000)
        try:
            world = client.get_world()
            message('Connected to CARLA server')
        except:
            try:
                warn('There seems to be a problem with your CARLA server. Retrying with WSL address...')
                client = carla.Client('172.18.112.1', 2000) # the host IP can be found with $(hostname).local from WSL
                world = client.get_world()
                message('Connected to CARLA server')
            except:
                raise PilotError('Connection to CARLA simulator failed. Check your CARLA installation, confirm simulator is running on port 2000.\nIf in WSL, refer to the troubleshooting guide for tips.')
        time = int(input('Enter the time you need the generator to run for (in minutes) >> '))
        clear()
        collector = Collector(world, time)

    def run_3():
        'Predict on a single video frame'
        print("Doing 3")

    def run_4():
        'Predict on live video feed'
        raise PilotError("Um sorry bruh. Live video prediction isn't available yet. I'm working on it keep an eye here.")

    def run_5():
        'Wrap up. I wanna quit.'
        message('Hope you enjoyed PilotNet. Report any issues on GitHub..')

    @staticmethod
    def execute(user_input):
        task_name = f'run_{user_input}'
        try:
            menu = getattr(Menu, task_name)
            clear()
        except AttributeError:
            shitquotes = [
                'Uh huh, where are your eyes at? Open sesame...',
                "Now what's up with that?",
                'Um sorry not on this menu...',
                "Sorry I couldn't read your mind. Come again?",
                "Good choice, congrats. Now try again."]
            raise PilotError(random.choice(shitquotes))
        else:
            menu()
    
    @staticmethod
    def generate_instructions():
        do_methods = [m for m in dir(Menu) if m.startswith('run_')]
        menu_string = "\n".join(
            [f'{method[-1]}.  {getattr(Menu, method).__doc__}' for method in do_methods])
        print(menu_string)
    
    @staticmethod
    def run():
        user_input = 0
        while(user_input != 5):
            clear()
            Menu.generate_instructions()
            user_input = int(input("Enter your choice >> "))
            try:
                Menu.execute(user_input)
            except PilotError:
                input('Press [ENTER] to continue')
            except KeyboardInterrupt:
                message('Hope you enjoyed using PilotNet. Report any issues on GitHub.')

def main():
    Menu.run()

if __name__ == '__main__':
    main()